### ISSUE TITLE
config

### ISSUE THREAD

**Issue by aecom** [EricAndrechek/homebridge-display#42] opened 2020-09-05 05:34 UTC
hi when adding the config home bridge fails 
any idea

**Comment by EricAndrechek** [comment] 2020-09-05 13:37
Could you paste the output from the log in debug mode? My only ideas without seeing that would be that either a widget is misconfigured or that the client is on a different version from the server.

**Comment by orangewolf** [comment] 2020-09-06 07:14
I'm seeing what I think @aecom was describing.  My set up is on HOOBs running on a Mac Mini.  This is the config that was added when I installed and configured via the UI

```
        {
            "platform": "homebridge-display",
            "plugin_map": {
                "plugin_name": "homebridge-display"
            },
            "Config": {
                "background": "https://i.postimg.cc/MpjZQcnn/background-image.jpg",
                "app_id": "https://i.postimg.cc/jjCsX4gH/home-black-ios.png",
                "private": false,
                "port": 6969,
                "customTitle": "Home2.0"
            },
            "Boxes": {
                "Box1": "Accessory Control",
                "Box2": "News",
                "Box3": "blank",
                "Box4": "blank",
                "Box5": "blank",
                "Box6": "blank"
            },
            "Newsfeed": {
                "delay": 60,
                "feed": [
                    "http://rss.cnn.com/rss/cnn_tech.rss"
                ]
            }
        }
```

This is what I see in the logs when homebridge tries to start.  Removing the plugin returns homebridge to working:

```
9/6/2020, 12:09:51 AM Homebridge Version: 2.5
9/6/2020, 12:09:51 AM Plugin Version: 0.4.11
9/6/2020, 12:09:51 AM found subnet for 192.168.1.52 on interface ip 192.168.1.9
9/6/2020, 12:09:51 AM uncaughtException: instance.accessories is not a function
9/6/2020, 12:09:51 AM TypeError: instance.accessories is not a function
    at Server.loadPlatformAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:357:18)
    at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:286:26)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:86:18)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
    at Module._compile (internal/modules/cjs/loader.js:736:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
    at Function.Module._load (internal/modules/cjs/loader.js:560:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:801:12)
    at executeUserCode (internal/bootstrap/node.js:526:15)
    at startMainThreadExecution (internal/bootstrap/node.js:439:3)
9/6/2020, 12:09:51 AM uncaughtException: instance.accessories is not a function
```

Any help would be appreciated =-)

**Comment by EricAndrechek** [comment] 2020-09-15 12:58
Hi, @orangewolf I am really struggling to diagnose what is causing your issue, would you be interested and willing to chat further about this in the [Homebridge Discord server](https://discord.gg/6u3uvj5) in the homebridge-display channel?

**Comment by aecom** [comment] 2020-09-18 03:55
hi is there any solution for this error ?

**Comment by EricAndrechek** [comment] 2020-09-18 12:32
I've been unable to diagnose it further based on the log, would you be interested and willing to chat further about this in the Homebridge Discord server in the homebridge-display channel? @aecom

**Comment by orangewolf** [comment] 2020-09-18 17:07
@EricAndrechek yes. i won't have a chance this week, but I'll circle back to it Monday (don't mean to ghost on you, day job got hectic this week)

**Comment by EricAndrechek** [comment] 2020-12-07 21:21
Closing this for now as there hasn't been any progress or updates and I've been unable to reproduce it myself. Currently, I suspect it is something to do with how HOOBs registers plugins vs Homebridge's method. Feel free to reopen it if need be.

**Closed by EricAndrechek** 2020-12-07 21:21 UTC
Labels: bug, in progress
